; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "CBT Simulator"
#define MyAppVersion "0.2.39"
#define MyAppPublisher "Yafea"
#define MyAppExeName "CBT Simulator.exe"

[Setup]
AppId={{A130BA2A-F8DA-4AC6-9D9E-96E012C5FCF8}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
#ifdef Beta
    OutputDir=Releases\Beta
    OutputBaseFilename=CBT_Simulator_{#MyAppVersion}_beta_setup
#else
    OutputDir=Releases
    OutputBaseFilename=CBT_Simulator_{#MyAppVersion}_setup
#endif
SetupIconFile=yafea.ico
UninstallDisplayIcon={app}\yafea.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:";

[Files]
Source: "Publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
Root: HKLM; Subkey: "SOFTWARE\Yafea\CBT"; ValueType: string; ValueName: "ConnectionString"; ValueData: "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA02AVo/nxBUiy56v1x4jTYgQAAAACAAAAAAAQZgAAAAEAACAAAACxAPSWIWS0ij7gDhj53ir0mZSgIwyMuAwHtZVQZPhN6wAAAAAOgAAAAAIAACAAAABbIteFJgCtwG3Juw7m6aEKfH4dM0OVqbLZmHQhAWV6h9AAAADyNtS3S8jphFehu3YMRKTbObY5TF2AVkaOSq2wCsA6wBhg2ZTHa9oNjArWVC1V3tIpi9EE64IPbfrTO/d3W3RRLuyolrcEOnGSuQhwvgRrAy4A5V7qV3Krn59rp6GJlpE8GbJEbX5Nh0nxT4Rtq3l2OyJOKgyyTFFTkYAUvzWJJhZcm55XzRlIGkOup27Ug9wlpW+2XqtpqHu1TI8mVxBMBO2Wq013UtSCWmQBeIYmRhovXOY3YZKb+SCSA3si/YjnPYV6xZts/l5xxiil7v+XQAAAALf3Dt83nsMrN8P9F1mcD429GLeCR7BEIT5wJxZLnqzdfo5OkWGjg/dS1FbAd6iwhFNNeFKijFJ5+5dKznTwetI="; Flags: uninsdeletekey;

[Dirs]
Name: "{commonappdata}\{#MyAppName}\Data";

[UninstallDelete]
Type: filesandordirs; Name: "{commonappdata}\{#MyAppName}";

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: waituntilterminated postinstall skipifsilent;

