; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "CBT Simulator"
#define MyAppPublisher "Yafea"
#define MyAppExeName "CBT Simulator.exe"
#define MySQLServerrName "MySQL80"
#define Major 0
#define Minor 2
#define Patch 13

[Setup]
AppId={{A130BA2A-F8DA-4AC6-9D9E-96E012C5FCF8}}
AppName={#MyAppName}
AppVersion={#Major}.{#Minor}.{#Patch}
VersionInfoVersion={#Major}.{#Minor}.{#Patch}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=CBT_Simulator_{#Major}_{#Minor}_{#Patch}_setup
OutputDir=Releases
SetupIconFile=yafea.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:";

[Files]
Source: "Publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Dirs]
Name: "{userappdata}\{#MyAppName}\Data";

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]

Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: waituntilterminated postinstall skipifsilent;
